#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# Configuration of HAproxy
server_config=\
"
frontend  sunny-frontend
        bind *:80
        mode http
        default_backend sunny-backend
backend sunny-backend
        balance roundrobin
        server	194764-web-01 54.175.144.21 check
	server	194764-web-02 18.204.10.91 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart