#!/usr/bin/env bash
#mysql backup
PASSWORD="$1"
FILENAME="backup.sql"
DATE="$(date +%d-%m-%Y)"
mysqldump --all-databases -u root --password="$1" > "$FILENAME"
#sudo mysqldump -u root -p "$PASSWORD" --all-databases > "$FILENAME"
tar -czvf "$DATE".tar.gz "$FILENAME"