#!/usr/bin/env bash
# The following process are done
#   Creates file /var/run/myscript.pid that contains a script PID.
#   Prints "To infinity and beyond" indefinitely
#   Prints "I hate the kill command" when a SIGTERM
#   Prints "Y U no love me?!" when receiving a SIGINT
#   Deletes file /var/run/myscript.pid and terminates when
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
