#!/usr/bin/env bash
# Prints contents of file /etc/passwd.
# Script should only display:
#     the username
#    the user id
#    The home directory path for user
while read -r file; 
do
    echo "$file" | cut -d ':' -f 1,3,6
done</etc/passwd
