#!/usr/bin/env bash
# Script that prints contents of file /etc/passwd,
# With the while loop + IFS.

while IFS=: read -r line1 line2 line3 line4 line5 line6 line7; do
    echo "The user $line1 is part of the $line4 gang, lives in $line6 and rides $line7. $line3's place is protected by the passcode $line2, more info about the user here: $line5"

done</etc/passwd