#!/usr/bin/env bash
# Gives information about the school files
# Must use if and, else (case is forbidden)
# Script should check if file exists and print:
  # if file exists: school file exists
  # if file does not exist: school file does not exist
# If the file exists, print:
  # if file is empty: school file is empty
  # if file is not empty: school file is not empty
  # if file is regular file: school is a regular file
  # if file is not regular file: (nothing)

if [ -e "school" ]; then
   echo "school file exists"

   if [ -s "school" ]; then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi

   if [ -f "school" ]; then
      echo "school is a regular file"
   fi
else
   echo "school file does not exist"
fi
