#!/usr/bin/env bash
# A Program which installs ufw firewall and configures it
# to block all incoming and outgoing traffic on all ports
# except for the following ports 22, 80 and 443

#to install the firewall
sudo apt-get update
sudo apt-get install ufw

#checking if ufw is active or inactive if active disable first 
sudo ufw status

# Configuring Firewall to deny all incoming Traffic and allow outgoing
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Configuring Firewall to allow ports
sudo ufw allow 80/tcp
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp

#seeing what has been added
sudo ufw show added

#enable ufw 
sudo ufw enable

# Checking the status of Firewall Rules
sudo ufw status

# Redirecting all Traffic from port :8080 to :80
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80